name: Python package

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
          python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{matrix.python-version}}
        uses: actions/setup-python@v3
        with:
            python-version: ${{matrix.python-version}}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [-f requirements.txt]; then pip install -r requirements; fi


      - name: use secret
        run: echo ${{secrets.GITHUB_TOKEN}}
      - name: use secret
        run: echo ${{secrets.GITHUB_TOKEN}}
